### ISSUE TITLE
Missing icon for Anaconda leads to brokenness for live media

### ISSUE THREAD

**Issue by Conan-Kudo** [CentOS/centos-logos#1]
In `fedora-logos` and `generic-logos`, there are icons for Anaconda itself. However, this is missing from `centos-logos`, which causes things to look kind of broken when creating CentOS-based live media.

The missing icons are:

* `org.fedoraproject.AnacondaInstaller.svg` ([`fedora-logos` reference](https://pagure.io/fedora-logos/blob/master/f/icons/hicolor/scalable/apps/org.fedoraproject.AnacondaInstaller.svg))
* `org.fedoraproject.AnacondaInstaller-symbolic.svg` ([`fedora-logos` reference](https://pagure.io/fedora-logos/blob/master/f/icons/hicolor/symbolic/apps/org.fedoraproject.AnacondaInstaller-symbolic.svg))

Can these please be added and made available in CentOS Stream (both CS8 and CS9)?

**Comment by Conan-Kudo** [comment]
cc: @davide125, @michel-slm

**Comment by areguera** [comment]
The anaconda icon for CS8 and CS9 is at [icons/hicolor/48x48/apps/anaconda.png](https://github.com/CentOS/centos-logos/blob/c9/icons/hicolor/48x48/apps/anaconda.png). Could you please share a screenshot of the CentOS-based live media brokenness for visual reference?

**Comment by Conan-Kudo** [comment]
Here's what it looks like (ignore the RHEL references, [that's separately fixed](https://pagure.io/centos-sig-hyperscale/anaconda/c/32dede4a858792a6ff5ce57e4552ae42f35b17d3?branch=c8s-hs-v33.16.5.2)):

<img width="912" alt="Screen Shot 2021-06-27 at 7 12 49 PM" src="https://user-images.githubusercontent.com/276796/123562277-b73b5400-d77b-11eb-9824-a1e4e0543581.png">

**Comment by areguera** [comment]
Thank you very much! I am taking care of it.

**Comment by Conan-Kudo** [comment]
Symbolic icons need to be installed into `hicolor/symbolic/apps` instead of `hicolor/scalable/apps`

**Comment by areguera** [comment]
Sorry about the path mistake. Is it correct now?

**Comment by Conan-Kudo** [comment]
Yep!

**Comment by areguera** [comment]
Excellent! I am closing this issue but feel free to reopen or add comments if you need to (specially for screenshots showing the fix :)

**Comment by Conan-Kudo** [comment]
Once you've got it released into CS8 and CS9, for sure! 😉

**Comment by areguera** [comment]
@Conan-Kudo, there is a centos-logos build [available]( https://koji.mbox.centos.org/koji/buildinfo?buildID=18229) in case you want to make a manual test.

**Comment by Conan-Kudo** [comment]
Looks good now with today's compose!

<img width="912" alt="Screen Shot 2021-07-18 at 10 31 06 AM" src="https://user-images.githubusercontent.com/276796/126071144-d5d5c4dc-e13c-4484-9719-6d8bef0b85a0.png">

**Comment by areguera** [comment]
Good. Thanks for the screenshot. Now, wondering about the highlighted icon on the left, is it the expected one?
