### ISSUE TITLE
GitHub/Gitlab Avatar logos?

### ISSUE THREAD

**Issue by prarit** [CentOS/centos-logos#3]
@areguera , I'm @prarit and part of the Red Hat kernel team.  I was wondering if this project contained any logos that would look good for GitHub & GitLab Avatars?  I didn't see one but I might not be looking in the right spot.

**Comment by areguera** [comment]
Hi @prarit, the centos-logos project provides visual identity for CentOS distribution mainly. For the specific case of external use in GitHub and GitLab avatars, the CentOS symbol in this project would be fine considering the space available in such media. However, before using the CentOS symbol, please consider the [CentOS trademarks](https://www.centos.org/legal/trademarks/) to be sure your need is aligned with it.

**Comment by prarit** [comment]
Thanks @areguera :) I'm actually asking for a logo for the avatar in https://gitlab.com/redhat/centos-stream/src/kernel.  I was hoping there was a pre-configured logo we could use but it doesn't look that way.  I'll discuss on centos-devel or some other list and likely propose an MR to add an image to this project.

**Comment by areguera** [comment]
Does [this one](https://github.com/CentOS/centos-logos/blob/c9/icons/hicolor/256x256/apps/system-logo-icon.png) work for you?

**Comment by prarit** [comment]
It's definitely something I was looking at.

The unfortunate thing about GitLab is that its default USER avatars look very confusingly like the CentOS logo :(.  I was thinking about [your suggestion](https://github.com/CentOS/centos-logos/blob/c9/icons/hicolor/256x256/apps/system-logo-icon.png) but with "CentOS Stream" at the bottom in text, and calling it project-avatar.png?  

What do you think?

**Comment by areguera** [comment]
A [logo redesign](https://git.centos.org/centos/Artwork/issue/1) will be presented to CentOS Board very soon and I hope it helps to address your need. In the mid-time, I took your comment as reference for the following:

![centos-logo-v-stream](https://user-images.githubusercontent.com/5214519/132537993-55f6be7d-63b5-4e31-aacb-12f3e90c6f88.png)

Note that using a combination of symbol and words as avatars will reduce the visibility of both symbol and words. Probably making them unreadable. So, the symbol alone is preferred in these cases.

It is important to remark that we don't have a project-avatar. We do have the CentOS Symbol, the CentOS Type, and the CentOS Logo (a combination of CentOS Symbol + CentOS Type). If an official avatar is necessary, the CentOS Symbol would be the way to go. If the CentOS Symbol has visual issues in different contexts, it is worth knowing information and our duty to find a way of fixing it. In such cases, visual examples showing the issue are appreciated.

**Comment by prarit** [comment]
First of all, thanks :)  I'm also worried about the readability of the avatar.  I know my avatar <--- over there ;) ... has hard to read text.  I'm reaching out to the Red Hat Brand team to find out if we can do something similar for gitlab.com/redhat/rhel/src/kernel projects.

**Comment by areguera** [comment]
I close this issue for now. Feel free to reopen it or create a new one in case you need to.

Best regards.
